version: 2
registries:
  # https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/dependabot-2.0.json
  github-nuget-kinnekode:
    type: nuget-feed
    url: https://nuget.pkg.github.com/KinNeko-DE/index.json
    token: ${{ secrets.READ_PACKAGES_PAT }}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0 # disable, because i needxat least one item in the array
