FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim AS base
RUN apt-get update && apt-get upgrade -y && apt-get install -y curl

WORKDIR /app
EXPOSE 8080
EXPOSE 3118

USER $APP_UID

COPY ./publish .
ENTRYPOINT ["dotnet", "Restaurant.SvcOrder.dll"]

