version: '3.9'

services:
  restaurant-order-svc:
    image: restaurant.order-svc
    networks:
      - dev-net
    container_name: restaurant.order-svc
    build:
      dockerfile: dockerfile
    ports:
      - "3118:3118"
      - "80:8080"
    healthcheck:
      # test: ["CMD", "bin/grpc_health_probe-linux-amd64", "-addr=localhost:3118", "||", "echo %errorlevel%"]
      test: curl --fail http://localhost:8080/health/ready || exit 1
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 5
    environment:
    - DatabaseConnectionConfig__Host=restaurant-order-db
    - DatabaseConnectionConfig__Port=5432
    - DatabaseConnectionConfig__Database=orderdatabase
    - DatabaseConnectionConfig__User=orderuser
    - DatabaseConnectionConfig__Password=orderpassword
    - DatabaseConnectionConfig__MaxPoolSize=5
    - DatabaseConnectionConfig__SearchPath=order
    - DatabaseConnectionConfig__SslMode=Prefer
    - Serilog__Using=Serilog.Sinks.Console
    - Serilog__MinimumLevel__Default=Information
    - Serilog__MinimumLevel__Override__Microsoft=Warning
    - Serilog__MinimumLevel__Override__System=Warning
    - Serilog__MinimumLevel__Override__Microsoft.AspNetCore.Hosting.Diagnostics=Information
    - Serilog__WriteTo__0__Name=Console
    - Serilog__WriteTo__0__Args__theme=Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console
    - Serilog__WriteTo__0__Args__outputTemplate=[{Timestamp:o}] [{Level:u3}] [{Application}] [{Message}] [{Exception}] [{Properties:j}] {NewLine}
    - Serilog__Enrich=FromLogContext
    - Serilog__Properties__Application=restaurant.order-svc
networks:
  dev-net:
    name: restaurant-dev-net
    external: true