version: '3.9'
name: restaurant-order-db
services:
  restaurant-order-db:
    image: postgres
    container_name: restaurant-order-db
    networks:
      - project-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}'"]
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 5
  restaurant-order-db-patch:
    image: flyway/flyway
    command: migrate -user=${DB_USER} -password=${DB_PASSWORD} -url="jdbc:postgresql://restaurant-order-db:5432/${DB_DATABASE}" -schemas=${DB_SCHEMA} -locations='filesystem:/sql'
    networks:
      - project-network
    container_name: restaurant-order-db-patch
    depends_on:
      restaurant-order-db:
        condition: service_healthy
    volumes:
      - ./patch:/sql
  restaurant-order-db-patch-validate:
    image: flyway/flyway
    command: validate -user=${DB_USER} -password=${DB_PASSWORD} -url="jdbc:postgresql://restaurant-order-db:5432/${DB_DATABASE}" -schemas=${DB_SCHEMA} -locations='filesystem:/sql'
    networks:
      - project-network
    container_name: restaurant-order-db-patch-validate
    depends_on:
      restaurant-order-db-patch:
        condition: service_completed_successfully
    volumes:
      - ./patch:/sql
networks:
  project-network:
    name: restaurant
    external: true