version: '3.9'
services:
  restaurant-svcorder-db:
    image: postgres
    container_name: restaurant-svcorder--db
    networks:
      - dev-net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}'"]
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 5
  restaurant-svcorder-db-patch:
    image: flyway/flyway
    command: migrate -user=${DB_USER} -password=${DB_PASSWORD} -url="jdbc:postgresql://restaurant-svcorder-db:5432/${DB_DATABASE}" -schemas=${DB_SCHEMA} -locations='filesystem:/sql'
    networks:
      - dev-net
    container_name: restaurant-svcorder-db-patch
    depends_on:
      restaurant-svcorder-db:
        condition: service_healthy
    volumes:
      - ./patch:/sql
networks:
  dev-net:
    name: restaurant-dev-net
    external: true